#!/bin/sh

# - greeting

echo
echo "NUOPC Component Explorer"
echo "------------------------"


# - high level error checking

if [ $# != 1 ]; then
  echo "Usage: nuopcExplorer <path/component-mk-file>"
  echo "Exiting with error."
  echo
  exit 1
else
  if [ ! -f $1 ]; then
    echo "The argument does not appear to be a regular file!"
    echo "Exiting with error."
    echo
    exit 1
  fi
fi

if [ $ESMFMKFILE"x" = "x" ]; then
  echo "The ESMFMKFILE environment variable does not appear to be set!"
  echo "Exiting with error."
  echo
  exit 1
else
  if [ ! -f $ESMFMKFILE ]; then
    echo "The ESMFMKFILE environment variable does not appear to be set to a regular file!"
    echo "Exiting with error."
    echo
    exit 1
  fi
fi

# - output of gathered information

echo "Using ESMFMKFILE: " $ESMFMKFILE
echo "Testing .mk file: " $1
echo

# - value of four standard makefile arguments

echo "-- Obtaining values of the standard variables set in the .mk file ..."
gmake COMP=$1 output 
echo

# - build explorer application

echo "-- Building the explorer application using the component in the .mk file ..."
gmake COMP=$1 explorerApp 
echo


# - end output

