#!/bin/sh

#==============================================================================
# Earth System Modeling Framework
# Copyright 2002-2019, University Corporation for Atmospheric Research, 
# Massachusetts Institute of Technology, Geophysical Fluid Dynamics 
# Laboratory, University of Michigan, National Centers for Environmental 
# Prediction, Los Alamos National Laboratory, Argonne National Laboratory, 
# NASA Goddard Space Flight Center.
# Licensed under the University of Illinois-NCSA License.
#==============================================================================

# - greeting

echo
echo "NUOPC Component Explorer Script"
echo "-------------------------------"


# - high level error checking

if [ $# != 1 ] && [ $# != 2 ]; then
  echo "Usage: nuopcExplorerScript <path/component-mk-file> [<comp-label>]"
  echo "  The optional <comp-label> will be used as the component label"
  echo "Exiting with error."
  echo
  exit 1
else
  if [ ! -f $1 ]; then
    echo "The argument does not appear to be a regular file!"
    echo "Exiting with error."
    echo
    exit 1
  fi
fi

if [ $ESMFMKFILE"x" = "x" ]; then
  echo "The ESMFMKFILE environment variable does not appear to be set!"
  echo "Exiting with error."
  echo
  exit 1
else
  if [ ! -f $ESMFMKFILE ]; then
    echo "The ESMFMKFILE environment variable does not appear to be set to a regular file!"
    echo "Exiting with error."
    echo
    exit 1
  fi
fi

# - output of gathered information

echo "Using ESMFMKFILE: " $ESMFMKFILE
echo "Testing .mk file: " $1
echo

# - value of four standard makefile arguments

echo "-- Obtaining values of the standard variables set in the .mk file ..."
gmake COMP=$1 output 
echo

# - build explorer application

echo "-- Building the explorer application using the component in the .mk file ..."
gmake COMP=$1 nuopcExplorerApp FRONT_COMP_LABEL=$2

if [ $? -eq 0 ]
then
echo
echo "SUCCESS: nuopcExplorerApp successfully built"
else
echo
echo "FAILURE: nuopcExplorerApp failed to build"
fi

echo "...exiting nuopcExplorerScript."
echo

# - end output

